import { Body, Controller, Get, Param, ParseUUIDPipe, Patch, Post, Query, Req, UseGuards } from '@nestjs/common';
import { AuthGuard } from '../auth/auth.guard'; import { AuthenticatedRequest } from '../auth/auth.types'; import { CsrfGuard } from '../auth/csrf.guard';
import { PermissionGuard } from '../authorization/permission.guard'; import { RequirePermissions } from '../authorization/permissions.decorator';
import { WbsService } from './wbs.service'; import { bool, code, nullable, object, str } from './wbs-validation';
const auth=(r:AuthenticatedRequest)=>r.auth!; const ctx=(r:AuthenticatedRequest)=>({auth:auth(r),...(r.correlationId ? {correlationId:r.correlationId} : {})});
@Controller('wbs') export class WbsController{constructor(private readonly svc:WbsService){}
 @Get('projects') @UseGuards(AuthGuard,PermissionGuard) @RequirePermissions('wbs.wbs.view') async projects(@Req()r:AuthenticatedRequest){return{data:await this.svc.projects(auth(r))};}
 @Get('projects/:projectId') @UseGuards(AuthGuard,PermissionGuard) @RequirePermissions('wbs.wbs.view') async list(@Req()r:AuthenticatedRequest,@Param('projectId',new ParseUUIDPipe({version:'4'}))p:string){return{data:await this.svc.listWbs(auth(r),p)};}
 @Post('projects/:projectId') @UseGuards(AuthGuard,CsrfGuard,PermissionGuard) @RequirePermissions('wbs.wbs.create') async create(@Req()r:AuthenticatedRequest,@Param('projectId',new ParseUUIDPipe({version:'4'}))p:string,@Body()b:unknown){const x=object(b);return{data:await this.svc.createWbs(ctx(r),p,{wbsCode:code(str(x,'wbsCode',80),'wbsCode'),wbsName:str(x,'wbsName',200),parentId:nullable(x,'parentId',36),description:nullable(x,'description',10000)})};}
 @Patch('projects/:projectId/:id') @UseGuards(AuthGuard,CsrfGuard,PermissionGuard) @RequirePermissions('wbs.wbs.edit') async update(@Req()r:AuthenticatedRequest,@Param('projectId',new ParseUUIDPipe({version:'4'}))p:string,@Param('id',new ParseUUIDPipe({version:'4'}))id:string,@Body()b:unknown){const x=object(b);const d:any={};if(x.wbsCode!==undefined)d.wbsCode=code(str(x,'wbsCode',80),'wbsCode');if(x.wbsName!==undefined)d.wbsName=str(x,'wbsName',200);if(x.parentId!==undefined)d.parentId=nullable(x,'parentId',36);if(x.description!==undefined)d.description=nullable(x,'description',10000);if(x.isActive!==undefined)d.isActive=bool(x,'isActive');return{data:await this.svc.updateWbs(ctx(r),p,id,d)};}
}
@Controller('cost-codes') export class CostCodesController{constructor(private readonly svc:WbsService){}
 @Get() @UseGuards(AuthGuard,PermissionGuard) @RequirePermissions('wbs.cost_code.view') async list(@Req()r:AuthenticatedRequest,@Query('search')s?:string,@Query('active')a?:string){return{data:await this.svc.listCostCodes(auth(r),s?.trim()||undefined,a==='true'?true:a==='false'?false:undefined)};}
 @Post() @UseGuards(AuthGuard,CsrfGuard,PermissionGuard) @RequirePermissions('wbs.cost_code.create') async create(@Req()r:AuthenticatedRequest,@Body()b:unknown){const x=object(b);return{data:await this.svc.createCostCode(ctx(r),{costCode:code(str(x,'costCode',80),'costCode'),costName:str(x,'costName',200),description:nullable(x,'description',10000)})};}
 @Patch(':id') @UseGuards(AuthGuard,CsrfGuard,PermissionGuard) @RequirePermissions('wbs.cost_code.edit') async update(@Req()r:AuthenticatedRequest,@Param('id',new ParseUUIDPipe({version:'4'}))id:string,@Body()b:unknown){const x=object(b);const d:any={};if(x.costCode!==undefined)d.costCode=code(str(x,'costCode',80),'costCode');if(x.costName!==undefined)d.costName=str(x,'costName',200);if(x.description!==undefined)d.description=nullable(x,'description',10000);if(x.isActive!==undefined)d.isActive=bool(x,'isActive');return{data:await this.svc.updateCostCode(ctx(r),id,d)};}
}
