import { FormEvent,useState } from 'react';
import { Alert,Button,Card,CardContent,MenuItem,Stack,TextField,Typography } from '@mui/material';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { CostCodeRecord,wbsApi,WbsRecord } from '../api/wbs';

export function WbsPanel({permissions}:{permissions:string[]}){
 const qc=useQueryClient(); const canWbsCreate=permissions.includes('wbs.wbs.create'),canWbsEdit=permissions.includes('wbs.wbs.edit'),canWbsArchive=permissions.includes('wbs.wbs.archive');
 const canCostCreate=permissions.includes('wbs.cost_code.create'),canCostEdit=permissions.includes('wbs.cost_code.edit'),canCostArchive=permissions.includes('wbs.cost_code.archive');
 const [projectId,setProjectId]=useState(''); const [selected,setSelected]=useState<WbsRecord|null>(null); const [wf,setWf]=useState({wbsCode:'',wbsName:'',parentId:'',description:''});
 const [search,setSearch]=useState('');const [active,setActive]=useState('all');const [cost,setCost]=useState<CostCodeRecord|null>(null);const [cf,setCf]=useState({costCode:'',costName:'',description:''});
 const projects=useQuery({queryKey:['wbs','projects'],queryFn:wbsApi.projects}); const wbs=useQuery({queryKey:['wbs',projectId],queryFn:()=>wbsApi.list(projectId),enabled:Boolean(projectId)});
 const costs=useQuery({queryKey:['cost-codes',search,active],queryFn:()=>wbsApi.costCodes(search,active),enabled:permissions.includes('wbs.cost_code.view')});
 const refreshWbs=()=>qc.invalidateQueries({queryKey:['wbs',projectId]});const refreshCost=()=>qc.invalidateQueries({queryKey:['cost-codes']});
 const saveWbs=useMutation({mutationFn:()=>selected?wbsApi.update(projectId,selected.id,{...wf,parentId:wf.parentId||null}):wbsApi.create(projectId,{...wf,parentId:wf.parentId||null}),onSuccess:async()=>{setSelected(null);setWf({wbsCode:'',wbsName:'',parentId:'',description:''});await refreshWbs();}});
 const toggleWbs=useMutation({mutationFn:(x:WbsRecord)=>wbsApi.update(projectId,x.id,{isActive:!x.isActive}),onSuccess:refreshWbs});
 const saveCost=useMutation({mutationFn:()=>cost?wbsApi.updateCostCode(cost.id,cf):wbsApi.createCostCode(cf),onSuccess:async()=>{setCost(null);setCf({costCode:'',costName:'',description:''});await refreshCost();}});
 const toggleCost=useMutation({mutationFn:(x:CostCodeRecord)=>wbsApi.updateCostCode(x.id,{isActive:!x.isActive}),onSuccess:refreshCost});
 const editW=(x:WbsRecord)=>{setSelected(x);setWf({wbsCode:x.wbsCode,wbsName:x.wbsName,parentId:x.parentId??'',description:x.description??''});};
 const editC=(x:CostCodeRecord)=>{setCost(x);setCf({costCode:x.costCode,costName:x.costName,description:x.description??''});};
 const rows=wbs.data?.data??[]; const depth=(x:WbsRecord)=>{let d=0,p=x.parentId,guard=0;while(p&&guard++<50){d++;p=rows.find(r=>r.id===p)?.parentId??null;}return d;};
 return <Stack spacing={4}>
  <Stack spacing={2}><Typography variant="h6">Work Breakdown Structure</Typography><TextField select label="Project" value={projectId} onChange={e=>{setProjectId(e.target.value);setSelected(null)}}><MenuItem value="">Select Project</MenuItem>{(projects.data?.data??[]).map(p=><MenuItem key={p.id} value={p.id}>{p.projectCode} · {p.projectName}</MenuItem>)}</TextField>
  {wbs.isError?<Alert severity="error">Unable to load WBS.</Alert>:null}{rows.map(x=><Card key={x.id} variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between"><div><Typography fontWeight={600} sx={{pl:depth(x)*3}}>{x.wbsCode} · {x.wbsName}</Typography><Typography variant="body2" color="text.secondary" sx={{pl:depth(x)*3}}>{x.isActive?'Active':'Inactive'}{x.description?' · '+x.description:''}</Typography></div><Stack direction="row">{canWbsEdit?<Button onClick={()=>editW(x)}>Edit</Button>:null}{canWbsArchive?<Button onClick={()=>toggleWbs.mutate(x)}>{x.isActive?'Deactivate':'Reactivate'}</Button>:null}</Stack></Stack></CardContent></Card>)}
  {projectId&&(canWbsCreate||selected&&canWbsEdit)?<Stack component="form" spacing={2} onSubmit={(e:FormEvent)=>{e.preventDefault();saveWbs.mutate()}}><Typography>{selected?'Edit WBS':'Add WBS'}</Typography><TextField label="WBS Code" value={wf.wbsCode} onChange={e=>setWf({...wf,wbsCode:e.target.value})} required/><TextField label="WBS Name" value={wf.wbsName} onChange={e=>setWf({...wf,wbsName:e.target.value})} required/><TextField select label="Parent WBS" value={wf.parentId} onChange={e=>setWf({...wf,parentId:e.target.value})}><MenuItem value="">Root</MenuItem>{rows.filter(x=>x.id!==selected?.id).map(x=><MenuItem key={x.id} value={x.id}>{x.wbsCode} · {x.wbsName}</MenuItem>)}</TextField><TextField label="Description" value={wf.description} onChange={e=>setWf({...wf,description:e.target.value})}/><Button type="submit" variant="contained">Save WBS</Button></Stack>:null}</Stack>
  {permissions.includes('wbs.cost_code.view')?<Stack spacing={2}><Typography variant="h6">Cost Code Register</Typography><Stack direction={{xs:'column',md:'row'}} spacing={2}><TextField label="Search Cost Codes" value={search} onChange={e=>setSearch(e.target.value)} fullWidth/><TextField select label="Status" value={active} onChange={e=>setActive(e.target.value)} sx={{minWidth:180}}><MenuItem value="all">All</MenuItem><MenuItem value="true">Active</MenuItem><MenuItem value="false">Inactive</MenuItem></TextField>{canCostCreate?<Button onClick={()=>{setCost(null);setCf({costCode:'',costName:'',description:''})}}>New Cost Code</Button>:null}</Stack>
  {(costs.data?.data??[]).map(x=><Card key={x.id} variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between"><div><Typography fontWeight={600}>{x.costCode} · {x.costName}</Typography><Typography variant="body2" color="text.secondary">{x.isActive?'Active':'Inactive'}{x.description?' · '+x.description:''}</Typography></div><Stack direction="row">{canCostEdit?<Button onClick={()=>editC(x)}>Edit</Button>:null}{canCostArchive?<Button onClick={()=>toggleCost.mutate(x)}>{x.isActive?'Deactivate':'Reactivate'}</Button>:null}</Stack></Stack></CardContent></Card>)}
  {(canCostCreate||cost&&canCostEdit)?<Stack component="form" spacing={2} onSubmit={(e:FormEvent)=>{e.preventDefault();saveCost.mutate()}}><Typography>{cost?'Edit Cost Code':'Add Cost Code'}</Typography><TextField label="Cost Code" value={cf.costCode} onChange={e=>setCf({...cf,costCode:e.target.value})} required/><TextField label="Name" value={cf.costName} onChange={e=>setCf({...cf,costName:e.target.value})} required/><TextField label="Description" value={cf.description} onChange={e=>setCf({...cf,description:e.target.value})}/><Button type="submit" variant="contained">Save Cost Code</Button></Stack>:null}</Stack>:null}
 </Stack>;
}
